version: '2'
services:
  cassandra:
    build: ./cassandra
    ports:
      - "7000:7001"
      - "7070:7070"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    depends_on:
      - cassandra

